version: '3'
services:
    web:
        restart: always
        build:
            context: .
        ports:
          - "3434:3000"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
